/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-dim": "#295a5d",
        "inverse-primary": "#94a8f5",
        "secondary-fixed-dim": "#abdddf",
        "background": "#f9f9f7",
        "inverse-on-surface": "#9c9d9b",
        "tertiary-fixed": "#ffccb6",
        "on-tertiary-container": "#664232",
        "primary-fixed": "#94a8f5",
        "on-tertiary-fixed-variant": "#704c3b",
        "on-surface": "#2f3332",
        "on-primary-fixed-variant": "#183075",
        "secondary-container": "#b9ecee",
        "surface-tint": "#475ba2",
        "on-error-container": "#6e0523",
        "tertiary-fixed-dim": "#f0bea9",
        "surface-container-highest": "#e0e3e0",
        "on-primary": "#faf8ff",
        "on-surface-variant": "#5c605e",
        "on-primary-container": "#0c266c",
        "on-tertiary-fixed": "#503021",
        "surface-bright": "#f9f9f7",
        "error": "#a8364b",
        "primary-dim": "#3a4f95",
        "surface-variant": "#e0e3e0",
        "on-secondary-fixed-variant": "#326365",
        "on-secondary": "#e3feff",
        "surface-container-low": "#f3f4f2",
        "on-background": "#2f3332",
        "surface": "#f9f9f7",
        "tertiary": "#7c5645",
        "inverse-surface": "#0c0f0e",
        "secondary-fixed": "#b9ecee",
        "tertiary-dim": "#6f4b3a",
        "on-secondary-fixed": "#104648",
        "primary-container": "#94a8f5",
        "secondary": "#366769",
        "outline-variant": "#afb3b0",
        "on-primary-fixed": "#000c36",
        "primary": "#475ba2",
        "tertiary-container": "#ffccb6",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceeec",
        "on-secondary-container": "#27595b",
        "surface-container-high": "#e6e9e6",
        "outline": "#777c79",
        "surface-dim": "#d7dbd8",
        "primary-fixed-dim": "#869ae6",
        "error-dim": "#6b0221",
        "error-container": "#f97386",
        "on-tertiary": "#fff7f5",
        "on-error": "#fff7f7",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Plus Jakarta Sans"],
        label: ["Plus Jakarta Sans"],
      },
    },
  },
  plugins: [],
};
